POST http://localhost:8000/api/light/ HTTP/1.1
Content-Type: application/json 

{
     "user_id" : "khkh",
     "name" : "Jeremy Andy F. Ampatin",
     "birthdate" :"October 4, 2001",
     "username": "ampats11"
}

